app:
    resource: "@AppBundle/Controller/"
    type:     annotation

logout:
    path: /logout

profile:
    path:  /profile
    defaults:  { _controller: AppBundle:Default:profile }

logs:
    path:  /logs
    defaults:  { _controller: AppBundle:Server:log }

reset:
    path:  /reset
    defaults:  { _controller: AppBundle:Security:reset }

update:
    path:  /reset/{id}/{hash}
    defaults:  { _controller: AppBundle:Security:update }

home:
    path: /
    defaults:  { _controller: AppBundle:Default:index }

password:
    path: /password
    defaults:  { _controller: AppBundle:Default:password }

login:
    path: /login
    defaults:  { _controller: AppBundle:Security:login }

servers:
    path: /servers
    defaults:  { _controller: AppBundle:Server:list }

view_servers:
    path: /servers/{sid}
    defaults:  { _controller: AppBundle:Server:view }

json:
    path: /servers/{sid}/json
    defaults:  { _controller: AppBundle:Server:json }

settings:
    path: /admin/settings
    defaults:  { _controller: AppBundle:Settings:form }

clients:
    path: /admin/clients
    defaults:  { _controller: AppBundle:Clients:list }

client_new:
    path: /admin/clients/new
    defaults:  { _controller: AppBundle:Clients:new }

client_edit:
    path: /admin/clients/{cid}
    defaults:  { _controller: AppBundle:Clients:edit }

client_password:
    path: /admin/clients/password/{cid}
    defaults:  { _controller: AppBundle:Clients:password }

graph:
    path: /servers/{sid}/graph
    defaults:  { _controller: AppBundle:Server:graph }

novnc:
    path: /novnc/{sid}
    defaults:  { _controller: AppBundle:Novnc:view }

novnc_request:
    path: /novnc/{sid}/request
    defaults:  { _controller: AppBundle:Novnc:request }

plans:
    path: /admin/plans/new/{type}
    defaults:  { _controller: AppBundle:Plans:new }
