app:
    resource: "@AppBundle/Controller/"
    type:     annotation

logout:
    path: /logout

profile:
    path:  /profile
    defaults:  { _controller: AppBundle:Default:profile }

logs:
    path:  /logs
    defaults:  { _controller: AppBundle:Server:log }

reset:
    path:  /reset
    defaults:  { _controller: AppBundle:Security:reset }

update:
    path:  /reset/{id}/{hash}
    defaults:  { _controller: AppBundle:Security:update }

home:
    path: /
    defaults:  { _controller: AppBundle:Default:index }

password:
    path: /password
    defaults:  { _controller: AppBundle:Default:password }

login:
    path: /login
    defaults:  { _controller: AppBundle:Security:login }

servers:
    path: /servers
    defaults:  { _controller: AppBundle:Server:list }

view_servers:
    path: /servers/{sid}
    defaults:  { _controller: AppBundle:Server:view }

json:
    path: /servers/{sid}/json
    defaults:  { _controller: AppBundle:Server:json }
